### PR TITLE
jenkins/kola: use httpS URL for PXE boot

### PR DESCRIPTION
**Pull request by tormath1**
Follow-up of:
* https://github.com/flatcar-linux/mantle/pull/288
* https://github.com/flatcar-linux/Flatcar/issues/527

Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>

### CODE REVIEW

**Review by sayanchowdhury — APPROVED** [review]

**Comment by pothos** [comment]
Please do a CI run first, I don't know if the proxy uses the shorter chain

**Comment by pothos** [comment]
Also worth looking at the provisioning times - at least in the past I remember that ipxe seemed to download slower with https, hopefully that's not the case.

**Comment by jepio** [comment]
If the proxy fetches its own cert, then we'll need to look at making it use the shorter chain as well.

**Comment by jepio** [comment]
I switched the bucket cache to also use the shorter chain.

**Review by pothos — APPROVED** [review]

**Comment by tormath1** [comment]
I'll trigger a CI run once https://github.com/flatcar-linux/mantle/pull/288 will be merged - just to be sure and avoid any surprise for the next round of releases.

**Comment by pothos** [comment]
The issue is that `packet` does not build the pxe images, so `packet pxe` is what should be in `FORMAT_LIST_AMD64`

**Comment by tormath1** [comment]
@pothos thanks for the information - Equinix Metal are running as expected now with HTTPS URLs.

**Pull request merged**
